apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: symfony-k8s-web
    name: symfony-k8s-web
spec:
    ports:
        -   name: "9000"
            port: 9000
            targetPort: 9000
        -   name: "80"
            port: 80
            targetPort: 80
    selector:
        io.kompose.service: symfony-k8s-web
status:
    loadBalancer: {}
