apiVersion: apps/v1
kind: Deployment
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: symfony-k8s-web
    name: symfony-k8s-web
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: symfony-k8s-web
    strategy:
        type: Recreate
    template:
        metadata:
            creationTimestamp: null
            labels:
                io.kompose.network/symfony-k8s: "true"
                io.kompose.service: symfony-k8s-web
        spec:
            containers:
                -   image: registry-url/symfony-k8s-php
                    name: symfony-k8s-php
                    env:
                        -   name: PHP_IDE_CONFIG
                            value: serverName=docker
                        -   name: XDEBUG_SESSION
                            value: PHPSTORM
                    resources: {}
                    volumeMounts:
                        -   mountPath: /var/www/symfony
                            name: symfony-k8s-web-volume
                -   image: registry-url/symfony-k8s-nginx
                    name: symfony-k8s-nginx
                    ports:
                        -   containerPort: 80
                    resources: {}
                    volumeMounts:
                        -   mountPath: /var/www/symfony
                            name: symfony-k8s-web-volume
            restartPolicy: Always
            volumes:
                -   name: symfony-k8s-web-volume
                    persistentVolumeClaim:
                        claimName: symfony-k8s-web-pvc0
status: {}
