apiVersion: apps/v1
kind: Deployment
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: symfony-k8s-web
    name: symfony-k8s-web
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: symfony-k8s-web
    strategy:
        type: Recreate
    template:
        metadata:
            creationTimestamp: null
            labels:
                io.kompose.network/symfony-k8s: "true"
                io.kompose.service: symfony-k8s-web
        spec:
            containers:
                -   image: registry-url/symfony-k8s-php
                    name: symfony-k8s-php
                    resources: {}
                    volumeMounts:
                        -   name: shared-data
                            mountPath: /var/www/symfony/public/shared
                -   image: registry-url/symfony-k8s-nginx
                    name: symfony-k8s-nginx
                    ports:
                        -   containerPort: 80
                    resources: {}
                    volumeMounts:
                        -   name: shared-data
                            mountPath: /var/www/symfony/public/shared
            restartPolicy: Always
            volumes:
                -   name: shared-data
                    emptyDir: {}
status: {}
