apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: symfony-k8s-postgresql
    name: symfony-k8s-postgresql
spec:
    ports:
        -   name: "5432"
            port: 5432
            targetPort: 5432
    selector:
        io.kompose.service: symfony-k8s-postgresql
status:
    loadBalancer: {}
