apiVersion: apps/v1
kind: Deployment
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: symfony-k8s-postgresql
    name: symfony-k8s-postgresql
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: symfony-k8s-postgresql
    strategy:
        type: Recreate
    template:
        metadata:
            creationTimestamp: null
            labels:
                io.kompose.network/symfony-k8s: "true"
                io.kompose.service: symfony-k8s-postgresql
        spec:
            containers:
                -   env:
                        -   name: POSTGRES_DB
                            value: symfony-k8s
                        -   name: POSTGRES_PASSWORD
                            value: very_strong_password
                        -   name: POSTGRES_USER
                            value: postgres
                    image: postgres:13.3-alpine
                    name: symfony-k8s-postgresql
                    ports:
                        -   containerPort: 5432
                    resources: {}
                    volumeMounts:
                        -   mountPath: /var/lib/postgresql/data
                            name: symfony-k8s-postgresql-volume-prod
            restartPolicy: Always
            volumes:
                -   name: symfony-k8s-postgresql-volume-prod
                    persistentVolumeClaim:
                        claimName: symfony-k8s-postgresql-pvc0-prod
status: {}
